INSERT INTO Golf.dbo.Course ([name]) VALUES ('Campgaw - Green');

INSERT INTO Golf.dbo.Hole (CourseId, Number, Par) VALUES (1,1,3);
INSERT INTO Golf.dbo.Hole (CourseId, Number, Par) VALUES (1,2,3);
INSERT INTO Golf.dbo.Hole (CourseId, Number, Par) VALUES (1,3,3);
INSERT INTO Golf.dbo.Hole (CourseId, Number, Par) VALUES (1,4,3);
INSERT INTO Golf.dbo.Hole (CourseId, Number, Par) VALUES (1,5,3);
INSERT INTO Golf.dbo.Hole (CourseId, Number, Par) VALUES (1,6,3);
INSERT INTO Golf.dbo.Hole (CourseId, Number, Par) VALUES (1,7,3);
INSERT INTO Golf.dbo.Hole (CourseId, Number, Par) VALUES (1,8,3);
INSERT INTO Golf.dbo.Hole (CourseId, Number, Par) VALUES (1,9,3);
INSERT INTO Golf.dbo.Hole (CourseId, Number, Par) VALUES (1,10,3);
INSERT INTO Golf.dbo.Hole (CourseId, Number, Par) VALUES (1,11,3);
INSERT INTO Golf.dbo.Hole (CourseId, Number, Par) VALUES (1,12,3);
INSERT INTO Golf.dbo.Hole (CourseId, Number, Par) VALUES (1,13,3);
INSERT INTO Golf.dbo.Hole (CourseId, Number, Par) VALUES (1,14,3);
INSERT INTO Golf.dbo.Hole (CourseId, Number, Par) VALUES (1,15,3);
INSERT INTO Golf.dbo.Hole (CourseId, Number, Par) VALUES (1,16,3);
INSERT INTO Golf.dbo.Hole (CourseId, Number, Par) VALUES (1,17,3);
INSERT INTO Golf.dbo.Hole (CourseId, Number, Par) VALUES (1,18,3);

INSERT INTO Golf.dbo.Person ([name]) VALUES ('Andrew Mamunes');
INSERT INTO Golf.dbo.Person ([name]) VALUES ('Jessica Drummond');

insert into  [Golf].[dbo].[HoleResult] (holeId, roundId, score, personId) values (1,1,4, 1);
  insert into  [Golf].[dbo].[HoleResult] (holeId, roundId, score, personId) values (2,1,4, 1);
  insert into  [Golf].[dbo].[HoleResult] (holeId, roundId, score, personId) values (3,1,4, 1);
  insert into  [Golf].[dbo].[HoleResult] (holeId, roundId, score, personId) values (4,1,4, 1);
  insert into  [Golf].[dbo].[HoleResult] (holeId, roundId, score, personId) values (5,1,4, 1);
  insert into  [Golf].[dbo].[HoleResult] (holeId, roundId, score, personId) values (6,1,4, 1);
  insert into  [Golf].[dbo].[HoleResult] (holeId, roundId, score, personId) values (7,1,4, 1);
  insert into  [Golf].[dbo].[HoleResult] (holeId, roundId, score, personId) values (8,1,4, 1);
  insert into  [Golf].[dbo].[HoleResult] (holeId, roundId, score, personId) values (9,1,4, 1);
  insert into  [Golf].[dbo].[HoleResult] (holeId, roundId, score, personId) values (10,1,4, 1);
  insert into  [Golf].[dbo].[HoleResult] (holeId, roundId, score, personId) values (11,1,4, 1);
  insert into  [Golf].[dbo].[HoleResult] (holeId, roundId, score, personId) values (12,1,4, 1);
  insert into  [Golf].[dbo].[HoleResult] (holeId, roundId, score, personId) values (13,1,4, 1);
  insert into  [Golf].[dbo].[HoleResult] (holeId, roundId, score, personId) values (14,1,4, 1);
  insert into  [Golf].[dbo].[HoleResult] (holeId, roundId, score, personId) values (15,1,4, 1);
  insert into  [Golf].[dbo].[HoleResult] (holeId, roundId, score, personId) values (16,1,4, 1);
  insert into  [Golf].[dbo].[HoleResult] (holeId, roundId, score, personId) values (17,1,4, 1);
  insert into  [Golf].[dbo].[HoleResult] (holeId, roundId, score, personId) values (18,1,4, 1);

  insert into  [Golf].[dbo].[HoleResult] (holeId, roundId, score, personId) values (1,1,4, 2);
  insert into  [Golf].[dbo].[HoleResult] (holeId, roundId, score, personId) values (2,1,4, 2);
  insert into  [Golf].[dbo].[HoleResult] (holeId, roundId, score, personId) values (3,1,4, 2);
  insert into  [Golf].[dbo].[HoleResult] (holeId, roundId, score, personId) values (4,1,4, 2);
  insert into  [Golf].[dbo].[HoleResult] (holeId, roundId, score, personId) values (5,1,4, 2);
  insert into  [Golf].[dbo].[HoleResult] (holeId, roundId, score, personId) values (6,1,4, 2);
  insert into  [Golf].[dbo].[HoleResult] (holeId, roundId, score, personId) values (7,1,4, 2);
  insert into  [Golf].[dbo].[HoleResult] (holeId, roundId, score, personId) values (8,1,4, 2);
  insert into  [Golf].[dbo].[HoleResult] (holeId, roundId, score, personId) values (9,1,4, 2);
  insert into  [Golf].[dbo].[HoleResult] (holeId, roundId, score, personId) values (10,1,4, 2);
  insert into  [Golf].[dbo].[HoleResult] (holeId, roundId, score, personId) values (11,1,4, 2);
  insert into  [Golf].[dbo].[HoleResult] (holeId, roundId, score, personId) values (12,1,4, 2);
  insert into  [Golf].[dbo].[HoleResult] (holeId, roundId, score, personId) values (13,1,4, 2);
  insert into  [Golf].[dbo].[HoleResult] (holeId, roundId, score, personId) values (14,1,4, 2);
  insert into  [Golf].[dbo].[HoleResult] (holeId, roundId, score, personId) values (15,1,4, 2);
  insert into  [Golf].[dbo].[HoleResult] (holeId, roundId, score, personId) values (16,1,4, 2);
  insert into  [Golf].[dbo].[HoleResult] (holeId, roundId, score, personId) values (17,1,4, 2);
  insert into  [Golf].[dbo].[HoleResult] (holeId, roundId, score, personId) values (18,1,4, 2);